name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  ### TODO
  #docker:

  ### TODO 
  #helm:

  bin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Set $GOPATH
        run: |
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "PATH=$PATH:$GOPATH/bin" >> $GITHUB_ENV

    - name: Get Dependencies
      run: go get -v -t -d ./...
      
    - name: Build
      run: make build
